/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.44                          *
*        Compiled Nov 10 2017, 08:53:57                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include <stdio.h>
#include <string.h>
#include "stdlib.h"
#include "stdbool.h"

struct Operate
{
    double ch1_sta; //0 refer to off
    double ch2_sta;
    int window_status;
    double ch_setting[4];
    int inpt_count;
    char sets[8];
};

extern struct Operate *ops_ptr;
extern WM_HWIN CreateMain(void);
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_FRAMEWIN_0 (GUI_ID_USER + 0x00)
#define ID_BUTTON_0 (GUI_ID_USER + 0x01)
#define ID_BUTTON_1 (GUI_ID_USER + 0x02)
#define ID_BUTTON_2 (GUI_ID_USER + 0x03)
#define ID_BUTTON_3 (GUI_ID_USER + 0x04)
#define ID_BUTTON_4 (GUI_ID_USER + 0x05)
#define ID_BUTTON_5 (GUI_ID_USER + 0x06)
#define ID_BUTTON_6 (GUI_ID_USER + 0x07)
#define ID_BUTTON_7 (GUI_ID_USER + 0x08)
#define ID_BUTTON_8 (GUI_ID_USER + 0x09)
#define ID_BUTTON_9 (GUI_ID_USER + 0x0A)
#define ID_BUTTON_10 (GUI_ID_USER + 0x0B)
#define ID_BUTTON_11 (GUI_ID_USER + 0x0C)
#define ID_BUTTON_12 (GUI_ID_USER + 0x0D)
#define ID_TEXT_0 (GUI_ID_USER + 0x0E)
#define ID_RADIO_0 (GUI_ID_USER + 0x0F)
#define ID_BUTTON_13 (GUI_ID_USER + 0x10)

// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
    {FRAMEWIN_CreateIndirect, "KeyBoard", ID_FRAMEWIN_0, 0, 0, 480, 272, 0, 0x0, 0},
    {BUTTON_CreateIndirect, "1", ID_BUTTON_0, 0, 0, 70, 62, 0, 0x0, 0},
    {BUTTON_CreateIndirect, "4", ID_BUTTON_1, 0, 63, 70, 62, 0, 0x0, 0},
    {BUTTON_CreateIndirect, "7", ID_BUTTON_2, 0, 125, 70, 62, 0, 0x0, 0},
    {BUTTON_CreateIndirect, "0", ID_BUTTON_3, 71, 187, 70, 62, 0, 0x0, 0},
    {BUTTON_CreateIndirect, "2", ID_BUTTON_4, 71, 0, 70, 62, 0, 0x0, 0},
    {BUTTON_CreateIndirect, "3", ID_BUTTON_5, 141, 0, 70, 62, 0, 0x0, 0},
    {BUTTON_CreateIndirect, "6", ID_BUTTON_6, 141, 63, 70, 62, 0, 0x0, 0},
    {BUTTON_CreateIndirect, "5", ID_BUTTON_7, 71, 63, 70, 62, 0, 0x0, 0},
    {BUTTON_CreateIndirect, "8", ID_BUTTON_8, 71, 125, 70, 62, 0, 0x0, 0},
    {BUTTON_CreateIndirect, "9", ID_BUTTON_9, 141, 125, 70, 62, 0, 0x0, 0},
    {BUTTON_CreateIndirect, "OK", ID_BUTTON_10, 360, 150, 80, 80, 0, 0x0, 0},
    {BUTTON_CreateIndirect, ".", ID_BUTTON_11, 141, 187, 70, 62, 0, 0x0, 0},
    {BUTTON_CreateIndirect, "C", ID_BUTTON_12, 0, 187, 70, 62, 0, 0x0, 0},
    {TEXT_CreateIndirect, "TEXT", ID_TEXT_0, 208, 49, 220, 40, 0, 0x0, 0},
    {BUTTON_CreateIndirect, "back", ID_BUTTON_13, 240, 150, 80, 80, 0, 0x0, 0},
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/

static void build_str(char *str_p, int st, char *inpts)
{
    for (int i = 0; i < sizeof(str_p); i++)
        str_p[i] = '\0';
    if (st == 0 || st == 1)
        strcat(str_p, "CH1: ");
    else
        strcat(str_p, "CH2: ");

    strcat(str_p, inpts);
    strcat(str_p, " ");

    if (st == 0 || st == 2)
        strcat(str_p, "V");
    else
        strcat(str_p, "A");
}

static void _cbDialog(WM_MESSAGE *pMsg)
{
    WM_HWIN hItem;
    WM_HWIN text_Item;
    int NCode;
    int Id;
    char text_x[20] = "";
    double vall;
    // USER START (Optionally insert additional variables)
    // USER END

    switch (pMsg->MsgId)
    {
    case WM_INIT_DIALOG:
        WINDOW_SetBkColor(pMsg->hWin, GUI_BLACK);
        //
        // Initialization of 'btn1'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
        BUTTON_SetFont(hItem, GUI_FONT_24_1);
        //
        // Initialization of 'btn4'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
        BUTTON_SetFont(hItem, GUI_FONT_24_1);
        //
        // Initialization of 'btn7'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);
        BUTTON_SetFont(hItem, GUI_FONT_24_1);
        //
        // Initialization of 'btn0'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_3);
        BUTTON_SetFont(hItem, GUI_FONT_24_1);
        //
        // Initialization of 'btn2'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_4);
        BUTTON_SetFont(hItem, GUI_FONT_24_1);
        //
        // Initialization of 'btn3'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_5);
        BUTTON_SetFont(hItem, GUI_FONT_24_1);
        //
        // Initialization of 'btn6'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_6);
        BUTTON_SetFont(hItem, GUI_FONT_24_1);
        //
        // Initialization of 'btn5'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_7);
        BUTTON_SetFont(hItem, GUI_FONT_24_1);
        //
        // Initialization of 'btn8'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_8);
        BUTTON_SetFont(hItem, GUI_FONT_24_1);
        //
        // Initialization of 'btn9'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_9);
        BUTTON_SetFont(hItem, GUI_FONT_24_1);
        //
        // Initialization of 'btn_ok'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_10);
        BUTTON_SetFont(hItem, GUI_FONT_24_1);
        //
        // Initialization of 'btn_dot'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_11);
        BUTTON_SetFont(hItem, GUI_FONT_24_1);
        //
        // Initialization of 'btn_c'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_12);
        BUTTON_SetFont(hItem, GUI_FONT_24_1);
        //
        // Initialization of 'Text'
        //
        text_Item = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
        TEXT_SetFont(text_Item, GUI_FONT_32_1);
        TEXT_SetTextAlign(text_Item, GUI_TA_HCENTER | GUI_TA_VCENTER);
        TEXT_SetTextColor(text_Item, GUI_MAKE_COLOR(0x000000FF));
        build_str(text_x, ops_ptr->window_status, "0");
        TEXT_SetText(text_Item, text_x);

        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_13);
        BUTTON_SetFont(hItem, GUI_FONT_24_1);
        // USER START (Optionally insert additional code for further widget initialization)
        // USER END
        break;
    case WM_NOTIFY_PARENT:
        text_Item = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
        Id = WM_GetId(pMsg->hWinSrc);
        NCode = pMsg->Data.v;
        switch (Id)
        {
        case ID_BUTTON_0: // Notifications sent by 'btn1'
            switch (NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
            case WM_NOTIFICATION_RELEASED:
                if (ops_ptr->inpt_count < 7)
                {
                    ops_ptr->sets[ops_ptr->inpt_count] = '1';
                    ops_ptr->inpt_count++;
                    build_str(text_x, ops_ptr->window_status, ops_ptr->sets);
                    TEXT_SetText(text_Item, text_x);
                }
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
                // USER START (Optionally insert additional code for further notification handling)
                // USER END
            }
            break;
        case ID_BUTTON_1: // Notifications sent by 'btn4'
            switch (NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
            case WM_NOTIFICATION_RELEASED:
                if (ops_ptr->inpt_count < 8)
                {
                    ops_ptr->sets[ops_ptr->inpt_count] = '4';
                    ops_ptr->inpt_count++;
                    build_str(text_x, ops_ptr->window_status, ops_ptr->sets);
                    TEXT_SetText(text_Item, text_x);
                }
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
                // USER START (Optionally insert additional code for further notification handling)
                // USER END
            }
            break;
        case ID_BUTTON_2: // Notifications sent by 'btn7'
            switch (NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
            case WM_NOTIFICATION_RELEASED:
                if (ops_ptr->inpt_count < 8)
                {
                    ops_ptr->sets[ops_ptr->inpt_count] = '7';
                    ops_ptr->inpt_count++;
                    build_str(text_x, ops_ptr->window_status, ops_ptr->sets);
                    TEXT_SetText(text_Item, text_x);
                }
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
                // USER START (Optionally insert additional code for further notification handling)
                // USER END
            }
            break;
        case ID_BUTTON_3: // Notifications sent by 'btn0'
            switch (NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
            case WM_NOTIFICATION_RELEASED:
                if (ops_ptr->inpt_count < 8)
                {
                    ops_ptr->sets[ops_ptr->inpt_count] = '0';
                    ops_ptr->inpt_count++;
                    build_str(text_x, ops_ptr->window_status, ops_ptr->sets);
                    TEXT_SetText(text_Item, text_x);
                }
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
                // USER START (Optionally insert additional code for further notification handling)
                // USER END
            }
            break;
        case ID_BUTTON_4: // Notifications sent by 'btn2'
            switch (NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
            case WM_NOTIFICATION_RELEASED:
                if (ops_ptr->inpt_count < 8)
                {
                    ops_ptr->sets[ops_ptr->inpt_count] = '2';
                    ops_ptr->inpt_count++;
                    build_str(text_x, ops_ptr->window_status, ops_ptr->sets);
                    TEXT_SetText(text_Item, text_x);
                }
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
                // USER START (Optionally insert additional code for further notification handling)
                // USER END
            }
            break;
        case ID_BUTTON_5: // Notifications sent by 'btn3'
            switch (NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
            case WM_NOTIFICATION_RELEASED:
                if (ops_ptr->inpt_count < 8)
                {
                    ops_ptr->sets[ops_ptr->inpt_count] = '3';
                    ops_ptr->inpt_count++;
                    build_str(text_x, ops_ptr->window_status, ops_ptr->sets);
                    TEXT_SetText(text_Item, text_x);
                }
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
                // USER START (Optionally insert additional code for further notification handling)
                // USER END
            }
            break;
        case ID_BUTTON_6: // Notifications sent by 'btn6'
            switch (NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
            case WM_NOTIFICATION_RELEASED:
                if (ops_ptr->inpt_count < 8)
                {
                    ops_ptr->sets[ops_ptr->inpt_count] = '6';
                    ops_ptr->inpt_count++;
                    build_str(text_x, ops_ptr->window_status, ops_ptr->sets);
                    TEXT_SetText(text_Item, text_x);
                }
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
                // USER START (Optionally insert additional code for further notification handling)
                // USER END
            }
            break;
        case ID_BUTTON_7: // Notifications sent by 'btn5'
            switch (NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
            case WM_NOTIFICATION_RELEASED:
                if (ops_ptr->inpt_count < 8)
                {
                    ops_ptr->sets[ops_ptr->inpt_count] = '5';
                    ops_ptr->inpt_count++;
                    build_str(text_x, ops_ptr->window_status, ops_ptr->sets);
                    TEXT_SetText(text_Item, text_x);
                }
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
                // USER START (Optionally insert additional code for further notification handling)
                // USER END
            }
            break;
        case ID_BUTTON_8: // Notifications sent by 'btn8'
            switch (NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
            case WM_NOTIFICATION_RELEASED:
                if (ops_ptr->inpt_count < 8)
                {
                    ops_ptr->sets[ops_ptr->inpt_count] = '8';
                    ops_ptr->inpt_count++;
                    build_str(text_x, ops_ptr->window_status, ops_ptr->sets);
                    TEXT_SetText(text_Item, text_x);
                }
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
                // USER START (Optionally insert additional code for further notification handling)
                // USER END
            }
            break;
        case ID_BUTTON_9: // Notifications sent by 'btn9'
            switch (NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
            case WM_NOTIFICATION_RELEASED:
                if (ops_ptr->inpt_count < 8)
                {
                    ops_ptr->sets[ops_ptr->inpt_count] = '9';
                    ops_ptr->inpt_count++;
                    build_str(text_x, ops_ptr->window_status, ops_ptr->sets);
                    TEXT_SetText(text_Item, text_x);
                }
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
                // USER START (Optionally insert additional code for further notification handling)
                // USER END
            }
            break;
        case ID_BUTTON_10: // Notifications sent by 'btn_ok'
            switch (NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
            case WM_NOTIFICATION_RELEASED:
                vall = atof(ops_ptr->sets);
                for (int i = 0; i < 8; i++)
                    ops_ptr->sets[i] = '\0';
                ops_ptr->inpt_count = 0;
                ops_ptr->ch_setting[ops_ptr->window_status] = vall;
                CreateMain();
                break;
            }
            break;
        case ID_BUTTON_11: // Notifications sent by 'btn_dot'
            switch (NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
            case WM_NOTIFICATION_RELEASED:
                if (ops_ptr->inpt_count < 8)
                {
                    ops_ptr->sets[ops_ptr->inpt_count] = '.';
                    ops_ptr->inpt_count++;
                    build_str(text_x, ops_ptr->window_status, ops_ptr->sets);
                    TEXT_SetText(text_Item, text_x);
                }
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
                // USER START (Optionally insert additional code for further notification handling)
                // USER END
            }
            break;
        case ID_BUTTON_12: // Notifications sent by 'btn_c'
            switch (NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
            case WM_NOTIFICATION_RELEASED:
                for (int i = 0; i < 8; i++)
                    ops_ptr->sets[i] = '\0';
                ops_ptr->inpt_count = 0;
                ops_ptr->sets[0] = '0';
                build_str(text_x, ops_ptr->window_status, ops_ptr->sets);
                TEXT_SetText(text_Item, text_x);

                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
                // USER START (Optionally insert additional code for further notification handling)
                // USER END
            }
            break;
        case ID_BUTTON_13: // Notifications sent by 'btn_back'
            switch (NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
            case WM_NOTIFICATION_RELEASED:
                // USER START (Optionally insert code for reacting on notification message)
                for (int i = 0; i < 8; i++)
                    ops_ptr->sets[i] = '\0';
                ops_ptr->inpt_count = 0;
                CreateMain();
                // USER END
                break;
                // USER START (Optionally insert additional code for further notification handling)
                // USER END
            }
            break;
            // USER START (Optionally insert additional code for further Ids)
            // USER END
        }
        break;
    // USER START (Optionally insert additional message handling)
    // USER END
    default:
        WM_DefaultProc(pMsg);
        break;
    }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateKeyboard
*/
WM_HWIN CreateKeyboard(void);
WM_HWIN CreateKeyboard(void)
{
    WM_HWIN hWin;

    hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
    return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
