
/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.44                          *
*        Compiled Nov 10 2017, 08:53:57                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include <stdio.h>
#include "stdlib.h"
#include <string.h>
#include "stdbool.h"
#include <scpi/scpi.h>
#include <scpi-def.h>

struct Operate
{
    double ch1_sta; //0 refer to off
    double ch2_sta;
    int window_status;
    double ch_setting[4];
    int inpt_count;
    char sets[8];
};

extern WM_HWIN CreateKeyboard(void);
extern struct Operate *ops_ptr;
extern char *tell;

static void build_str(char *str_p, int st, double value)
{
    for (int i = 0; i < sizeof(str_p); i++)
        str_p[i] = '\0';
    char buf[9];
    bool is_m = value < 1. && value != 0.;
    if (st == 0 || st == 1)
        strcat(str_p, "CH1: ");
    else
        strcat(str_p, "CH2: ");

    if (is_m)
        value *= 1000.;
    sprintf(buf, "%g", value);
    strcat(str_p, buf);
    strcat(str_p, " ");

    if (is_m)
        strcat(str_p, "m");

    if (st == 0 || st == 2)
        strcat(str_p, "V");
    else
        strcat(str_p, "A");
}

static void build_command(char *cmd_ptr)
{
    char aa[10];
    int is_ch2 = ops_ptr->window_status / 2;
    for (int i = 0; i < sizeof(cmd_ptr); i++)
        cmd_ptr[i] = '\0';
    if (is_ch2)
        strcat(cmd_ptr, "INST CH2\r\n*RST\r\n");
    else
        strcat(cmd_ptr, "INST CH1\r\n*RST\r\n");
    
    if (ops_ptr->ch_setting[0]==0. && ops_ptr->ch_setting[2]==0.)
    {
        strcat(cmd_ptr, "OUTP OFF\r\n");
        return;
    }
    
    strcat(cmd_ptr, "CONF:VOLT:DC ");
    sprintf(aa, "%g,%g", ops_ptr->ch_setting[0], ops_ptr->ch_setting[2]);
    strcat(cmd_ptr, aa);

    strcat(cmd_ptr, "\r\nCONF:CURR ");
    sprintf(aa, "%g,%g", ops_ptr->ch_setting[1], ops_ptr->ch_setting[3]);
    strcat(cmd_ptr, aa);
    strcat(cmd_ptr, "\r\nOUPT ON\r\n");
}
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_FRAMEWIN_0 (GUI_ID_USER + 0x00)
#define ID_TEXT_0 (GUI_ID_USER + 0x02)
#define ID_BUTTON_0 (GUI_ID_USER + 0x03)
#define ID_TEXT_1 (GUI_ID_USER + 0x04)
#define ID_BUTTON_1 (GUI_ID_USER + 0x05)
#define ID_BUTTON_2 (GUI_ID_USER + 0x07)
#define ID_BUTTON_3 (GUI_ID_USER + 0x08)
#define ID_TEXT_2 (GUI_ID_USER + 0x09)
#define ID_IMAGE_0 (GUI_ID_USER + 0x0A)

#define ID_IMAGE_0_IMAGE_0 0x00

// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/
/*********************************************************************
*
*       _acImage_0, "C:\Users\huliz\Desktop\Untitled.jpg", ID_IMAGE_0_IMAGE_0
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
    {FRAMEWIN_CreateIndirect, "Main Window", ID_FRAMEWIN_0, 0, 0, 480, 272, 0, 0x0, 0},
    {TEXT_CreateIndirect, "CH1: OFF", ID_TEXT_0, 30, 10, 170, 50, 0, 0x0, 0},
    {BUTTON_CreateIndirect, "CH1: 0 V", ID_BUTTON_0, 30, 70, 150, 70, 0, 0x0, 0},
    {TEXT_CreateIndirect, "CH2: OFF", ID_TEXT_1, 270, 10, 160, 50, 0, 0x0, 0},
    {BUTTON_CreateIndirect, "CH1: 0 A", ID_BUTTON_1, 30, 140, 150, 70, 0, 0x0, 0},
    {BUTTON_CreateIndirect, "CH2: 0 V", ID_BUTTON_2, 270, 70, 150, 70, 0, 0x0, 0},
    {BUTTON_CreateIndirect, "CH2: 0 A", ID_BUTTON_3, 270, 140, 150, 70, 0, 0x0, 0},
    {TEXT_CreateIndirect, "Command", ID_TEXT_2, 0, 210, 470, 40, 0, 0x0, 0},
};

/*********************************************************************
*
*       Static code   
*
**********************************************************************
*/
/*********************************************************************
*
*       _GetImageById
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE *pMsg)
{
    WM_HWIN hItem;
    int NCode;
    int Id;
    int cmd_id=0;

    char text_x[20] = "";
    char command[100] = "";
    // USER START (Optionally insert additional variables)
    // USER END

    switch (pMsg->MsgId)
    {
    case WM_INIT_DIALOG:
        //
        // Initialization of 'CH1:V(dis)'
        //

        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
        TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
        TEXT_SetFont(hItem, GUI_FONT_32_1);
        TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x000000FF));
        if (ops_ptr->ch_setting[0] != 0.)
        {
            build_str(text_x, 1, 0.);
            TEXT_SetText(hItem, text_x);
        }
        //
        // Initialization of 'CH1:V'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
        BUTTON_SetFont(hItem, GUI_FONT_24_1);
        build_str(text_x, 0, ops_ptr->ch_setting[0]);
        BUTTON_SetText(hItem, text_x);
        //
        // Initialization of 'CH2'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
        TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
        TEXT_SetFont(hItem, GUI_FONT_32_1);
        TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00FF0000));
        if (ops_ptr->ch_setting[2] != 0.)
        {
            build_str(text_x, 3, 0.);
            TEXT_SetText(hItem, text_x);
        }
        //
        // Initialization of 'CH1:A'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
        BUTTON_SetFont(hItem, GUI_FONT_24_1);
        build_str(text_x, 1, ops_ptr->ch_setting[1]);
        BUTTON_SetText(hItem, text_x);
        //
        // Initialization of 'CH2:V'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);
        BUTTON_SetFont(hItem, GUI_FONT_24_1);
        build_str(text_x, 2, ops_ptr->ch_setting[2]);
        BUTTON_SetText(hItem, text_x);
        //
        // Initialization of 'Button'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_3);
        BUTTON_SetFont(hItem, GUI_FONT_24_1);
        build_str(text_x, 4, ops_ptr->ch_setting[3]);
        BUTTON_SetText(hItem, text_x);
        //
        // Initialization of 'Text'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
        TEXT_SetFont(hItem, GUI_FONT_20_1);
        TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00FF0080));
        TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_TOP);
        build_command(command);
        SCPI_Input(&scpi_context, command, strlen(command));
        for (int i = 0; i < sizeof(command); i++)
        {
            if (command[i]=='\r'&&command[i+1]=='\n')
            {
                command[i] = ';';
                command[i+1] = ' ';
                if (cmd_id<45&&i>45)
                    command[cmd_id+1] = '\n';
                cmd_id=i;
            }
        }
        strcat(command, "\n\n");
        TEXT_SetText(hItem, command);
        // USER END
        break;

    case WM_NOTIFY_PARENT:
        Id = WM_GetId(pMsg->hWinSrc);
        NCode = pMsg->Data.v;
        switch (Id)
        {
        case ID_BUTTON_0: // Notifications sent by 'CH1:V'
            switch (NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
            case WM_NOTIFICATION_RELEASED:
                // USER START (Optionally insert code for reacting on notification message)
                ops_ptr->window_status = 0;
                CreateKeyboard();
                // USER END
                break;
                // USER START (Optionally insert additional code for further notification handling)
                // USER END
            }
            break;
        case ID_BUTTON_1: // Notifications sent by 'CH1:A'
            switch (NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
            case WM_NOTIFICATION_RELEASED:
                // USER START (Optionally insert code for reacting on notification message)
                ops_ptr->window_status = 1;
                CreateKeyboard();
                // USER END
                break;
                // USER START (Optionally insert additional code for further notification handling)
                // USER END
            }
            break;
        case ID_BUTTON_2: // Notifications sent by 'CH2:V'
            switch (NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
            case WM_NOTIFICATION_RELEASED:
                // USER START (Optionally insert code for reacting on notification message)
                ops_ptr->window_status = 2;
                CreateKeyboard();
                // USER END
                break;
                // USER START (Optionally insert additional code for further notification handling)
                // USER END
            }
            break;
        case ID_BUTTON_3: // Notifications sent by 'Button'
            switch (NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
            case WM_NOTIFICATION_RELEASED:
                ops_ptr->window_status = 3;
                CreateKeyboard();
                break;
                // USER START (Optionally insert additional code for further notification handling)
                // USER END
            }
            break;
            // USER START (Optionally insert additional code for further Ids)
            // USER END
        }
        break;
    // USER START (Optionally insert additional message handling)
    // USER END
    default:
        WM_DefaultProc(pMsg);
        break;
    }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateMain
*/
WM_HWIN CreateMain(void);
WM_HWIN CreateMain(void)
{
    WM_HWIN hWin;

    hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
    return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
